# Generated by Django 5.2.5 on 2025-09-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={},
        ),
    ]
