# Generated by Django 5.2.5 on 2025-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='userprofile/default-avatar.png', null=True, upload_to='userprofile/'),
        ),
    ]
