# Generated by Django 5.2.5 on 2025-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_note',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
