# Generated by Django 5.2.5 on 2025-09-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_note_orderproduct_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
