# Generated by Django 5.2.5 on 2025-09-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_line_1_order_address_line_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
